name: Maven Cache Example

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Ajustez la version du JDK selon vos besoins

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-build-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-build-

      - name: Build with Maven
        run: mvn clean install

      - name: Display the content of .m2/repository
        run: ls -la ~/.m2/repository
